data:
  data_dir: /Users/thomasmoore/Desktop/SNIPER_DEV/ATLAS/
  output_dir: /Users/thomasmoore/Desktop/SNIPER_DEV/
  flux_unc_cut: 80
  IAU_Names: SLSN_names.txt
mcmc:
  do_fireball: False
  mjd_minus: 100
  mjd_plus: 300
  nsteps_bazin: 1e4
  nsteps_fireball: 5
  nwalkers_bazin: 30
  nwalkers_fireball: 20
progress:
  plots: True
  progress_bar: True
