data:
  data_dir: /Users/thomasmoore/Desktop/SNIPER_DEV/ATLAS_TDEs/
  output_dir: /Users/thomasmoore/Desktop/SNIPER_DEV/
  flux_unc_cut: 80
  IAU_Names: 2022upj.txt
mcmc:
  mjd_minus: 300
  mjd_plus: 300
  nsteps_bazin: 1e5
  nsteps_fireball: 1e5
  nwalkers_bazin: 400
  nwalkers_fireball: 400
progress:
  plots: True
  progress_bar: True
